import Head from 'next/head'
import Header from './Header';
import  Main  from './Main';
import Footer from './Footer';

export default function Home() {
  // const [newLocations, setNewLocations] = useState([]);
  // function locationUpdateHandler(event) {
  //   event.preventDefault();
  //   // get a random reply from data.js
  //   // const randomReply = replies[Math.floor(Math.random() * replies.length)];
  //   // build an object representing the question and reply
  //   const newLocation = {
  //       location: event.target.location.value,
  //       minCustomers: event.target.min.value,
  //       maxCustomers: event.target.max.value,
  //       avgCustomers: event.target.avg.value,
  //   };
  //   //alert(event.target.question.value);
  //   //alert(randomReply);
  //   //setReply(randomReply);
  //   setNewLocations([...newLocations, newLocation]);
  // }
  
  return (
    <>
      <div
      >
        <Head>
          <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <Main/>
        <Footer/>
        
        
        
      </div>
    </>
  )
}
